name: hostel_mgmt
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  connectivity_plus: ^6.1.5
  get: ^4.7.2
  provider: ^6.1.5+1
  flutter_native_splash: ^2.4.6
  pull_to_refresh: ^2.0.0
  encrypt: ^5.0.3
  crypto: ^3.0.6
  shared_preferences: ^2.5.3
  http: ^1.5.0
  animated_segmented_tab_control: ^2.0.0
  timelines_plus: ^1.0.7
  go_router: ^16.2.0
  shimmer: ^3.0.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_dotenv: ^6.0.0
  dartz: ^0.10.1
  dotenv: ^4.2.0
  glassmorphism: ^3.0.0
  liquid_glass_renderer: ^0.1.1-dev.10
  smooth_page_indicator: ^1.2.1
  google_fonts: ^6.3.1
  flutter_inset_box_shadow: ^1.0.8
  material_segmented_control: ^5.0.1
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/spsu_logo.jpg
    - .env
    - packages/liquid_glass_renderer/assets/shaders/liquid_glass.frag
    - assets/user.png
    - assets/home.png
    - assets/profile_pic_demo.png
    - assets/calender_icon.png
    - assets/app_icon.png
    - assets/hostel_image.png
    - assets/app_icon1.png
    - assets/hero1.png
    - assets/monthly_calender.png
    - assets/today_calender.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/spsu_logo.jpg
  android: true
  ios: true
  web: true


flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon1.png"