name: hostel_dayout_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dartz: ^0.10.1
  internet_connection_checker: ^3.0.1
  hive: ^2.2.3
  http: ^1.5.0
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  go_router: ^16.1.0
  get_it: ^8.2.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  shimmer: ^3.0.0
  shadcn_ui: ^0.28.5
  flutter_speed_dial: ^7.0.0
  shadcn_flutter: ^0.0.38

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true
